-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2022-05-23 22:55:51 WEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE conta (
    codigo_conta NUMBER(9) NOT NULL,
    email        VARCHAR2(155) NOT NULL,
    senha        VARCHAR2(16) NOT NULL
);

ALTER TABLE conta ADD CONSTRAINT conta_pk PRIMARY KEY ( codigo_conta );

ALTER TABLE conta ADD CONSTRAINT conta_email_conta_un UNIQUE ( email );

CREATE TABLE meta (
    codigo_item              NUMBER(9) NOT NULL,
    descricao_item           VARCHAR2(155) NOT NULL,
    tipo_meta                VARCHAR2(155) NOT NULL,
    unidade_medida           CHAR(2) NOT NULL,
    descricao_unidade_medida VARCHAR2(155) NOT NULL
);

ALTER TABLE meta ADD CONSTRAINT meta_pk PRIMARY KEY ( codigo_item );

CREATE TABLE meta_usuario (
    codigo_usuario        NUMBER(9) NOT NULL,
    codigo_item           NUMBER(9) NOT NULL,
    data_inicio           DATE NOT NULL,
    valor_meta            NUMBER(3, 2) NOT NULL,
    data_termino_prevista DATE
);

ALTER TABLE meta_usuario ADD CONSTRAINT t_sht_meta_usuario_pk PRIMARY KEY ( codigo_usuario,
                                                                            codigo_item );

CREATE TABLE registro_meta (
    codigo_registro_meta NUMBER(9) NOT NULL,
    codigo_usuario       NUMBER(9) NOT NULL,
    codigo_item          NUMBER(9) NOT NULL,
    valor_realizado      NUMBER(3, 2) NOT NULL,
    data_realizacao      DATE NOT NULL
);

ALTER TABLE registro_meta ADD CONSTRAINT registro_meta_pk PRIMARY KEY ( codigo_registro_meta );

CREATE TABLE usuario (
    codigo_usuario     NUMBER(9) NOT NULL,
    codigo_conta       NUMBER(9) NOT NULL,
    nome_usuario       VARCHAR2(80) NOT NULL,
    data_nascimento    DATE NOT NULL,
    localidade         VARCHAR2(80),
    altura             NUMBER(3, 2) NOT NULL,
    valor_peso_inicial FLOAT(2) NOT NULL,
    pressao_arterial   VARCHAR2(10) NOT NULL
);

CREATE UNIQUE INDEX usuario__idx ON
    usuario (
        codigo_conta
    ASC );

ALTER TABLE usuario ADD CONSTRAINT usuario_pk PRIMARY KEY ( codigo_usuario );

ALTER TABLE meta_usuario
    ADD CONSTRAINT "META_USUARIO-META_FK" FOREIGN KEY ( codigo_item )
        REFERENCES meta ( codigo_item );

ALTER TABLE meta_usuario
    ADD CONSTRAINT "META_USUARIO-USUARIO_FK" FOREIGN KEY ( codigo_usuario )
        REFERENCES usuario ( codigo_usuario );

ALTER TABLE registro_meta
    ADD CONSTRAINT "REGISTRO_META-META_USUARIO_FK" FOREIGN KEY ( codigo_usuario,
                                                                 codigo_item )
        REFERENCES meta_usuario ( codigo_usuario,
                                  codigo_item );

ALTER TABLE usuario
    ADD CONSTRAINT "USUARIO-CONTA_FK" FOREIGN KEY ( codigo_conta )
        REFERENCES conta ( codigo_conta );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
